name: 'Add #ASKtool'
description: 'You can propose a new tool to be listed on the #ASKnet website.'
title: "Add #ASKtool: "
labels: [content-submit, new-asktool]
body:
  - type: markdown
    attributes:
      value: |
        Here you can submit your proposal for a new #ASKtool that you think should be shown on the #ASKnet website. 
                
  - type: input
    id: title
    attributes:
      label: Title
      description: "short heading of the tool"
    validations:
      required: true  

  - type: input
    id: subtitle
    attributes:
      label: Sub-Title
      description: "a short description / sentence"
    validations:
      required: true

  - type: textarea
    id: picture
    attributes:
      label: Picture
      description: You can upload an image by dragging & dropping into this textarea or clicking on the bottom of this textarea and selecting your image. 
    validations:
      required: false

  - type: input
    id: link
    attributes:
      label: Reference Link
      description: "a link to the tool"
    validations:
      required: false
